# 마크다운

##  넘파이 모듈과 판다스 모듈 버전확인하기

In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

In [3]:
import pandas as pd

In [4]:
pd.__version__

'0.25.1'

# 1. 벡터 알아보기

##  1차원 배열 : 벡터 만들기

In [5]:
vector= np.array([3,4,5])

In [6]:
vector

array([3, 4, 5])

## 2 차원으로 벡터 만들기

### 열벡터 만들기

In [7]:
vector_col = vector.reshape(3,1)

In [8]:
vector_col

array([[3],
       [4],
       [5]])

In [9]:
vector[:, np.newaxis]

array([[3],
       [4],
       [5]])

###  행벡터 만들기

In [10]:
vector_row = vector.reshape(1,3)

In [11]:
vector_row

array([[3, 4, 5]])

In [12]:
vector[np.newaxis, :]

array([[3, 4, 5]])

# 2. 행렬 만들기

## 다차원 배열로 만들기

In [13]:
ll = [[1,2,3,], [4,5,6]]

In [14]:
array = np.array(ll)

In [15]:
array

array([[1, 2, 3],
       [4, 5, 6]])

## 매트릭스 배열 만들기

In [16]:
matrix = np.matrix(ll)

In [17]:
matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
np.mat(ll)

matrix([[1, 2, 3],
        [4, 5, 6]])

# 3. 배열의 메타 정보와 데이터 확인하기

In [19]:
a = np.array(ll)

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6]])

## 데이터 알아보기

In [21]:
a.data

In [22]:
a.data.obj

array([[1, 2, 3],
       [4, 5, 6]])

## 데이터 내부는 일차원으로 관리

In [23]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

## 하나의 데이터를 처리하거나 확장할 때 기준 알아보기

In [24]:
a.strides

(24, 8)

## 차원과 형상 확인하기

In [25]:
a.ndim, a.shape

(2, (2, 3))

## 자료형과  각각의 원소 길이

In [26]:
a.dtype, a.itemsize

(dtype('int64'), 8)

# 4. 원소 선택하기

## 1 차원 배열의 원소 확인하기

In [27]:
b = np.arange(1,10)

In [28]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
len(b)

9

In [30]:
b.size

9

## 순방향 인덱스로 색인 연산으로 원소 읽어오기

In [31]:
b[0]

1

In [32]:
b[8]

9

### 인덱스 범위는 0 부터 8까지 총 9개  

In [33]:
try :
    b[9]
except Exception as e :
    print(e)

index 9 is out of bounds for axis 0 with size 9


## 역방향 인덱스로 색인연산

In [34]:
b[-1]

9

In [35]:
b[-8]

2

In [36]:
b[-9]

1

In [37]:
try :
    b[-10]
except Exception as e :
    print(e)

index -10 is out of bounds for axis 0 with size 9


# 5. 슬라이스로 여러 원소 가져오기

## 전체 원소 가져오기

In [38]:
b[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b[:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 마지막 원소를 제외하고 가져오기

In [40]:
b[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
b[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

## 역방향으로 가져오기

In [42]:
b[-1:-9:-1]

array([9, 8, 7, 6, 5, 4, 3, 2])

# 5. 행렬 연산 처리

## 원소별 계산

In [43]:
c = np.arange(1,10).reshape(3,3)

In [44]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 원소별  산술 연산

In [45]:
c + c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [46]:
c * c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

##  행렬의 곱 처리

### 행렬곱

In [47]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [48]:
c @ c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [49]:
np.matmul(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### 벡터간의 내적 : 스칼라 곱 처리

In [50]:
c[0]

array([1, 2, 3])

In [51]:
c[:, 0]

array([1, 4, 7])

In [52]:
np.dot(c[0], c[:,0])

30

In [53]:
c[0] @ c[:,0]

30

In [54]:
np.matmul(c[0], c[:,0])

30

# 6.  평균, 분산, 표준편차 계산하기

## 모집단 평균, 분산, 표준편차

In [55]:
c.mean()

5.0

In [56]:
np.average(c)

5.0

In [57]:
c.var()

6.666666666666667

In [58]:
c.std()

2.581988897471611

## 샘플 분산 표준편차

In [59]:
c.var(ddof=1)

7.5

In [60]:
c.std(ddof=1)

2.7386127875258306

##  범위 처리

In [61]:
c.min()

1

In [62]:
c.max()

9

In [63]:
c.max() - c.min()

8

# 7. 행렬의 구조 알아보기

## 행렬의 형상 바꾸기

In [64]:
d = np.arange(1,13).reshape(3,4)

In [65]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 전치 행렬 알아보기

In [66]:
d.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [67]:
np.transpose(d)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [68]:
np.swapaxes(d, 0,1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 8. 선형대수 알아보기

## 행렬의 랭크 알아보기

In [69]:
e = np.arange(1,17).reshape(4,4)

In [70]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 행렬식이 0 이면 랭크의 개수가 행렬의 차수보다 작다 

In [71]:
np.linalg.det(e)

-1.820448242817726e-31

In [72]:
np.allclose(np.linalg.det(e), 0)

True

In [73]:
np.linalg.matrix_rank(e)

2

### 행렬식이 0이 아니면 랭크의 개수가 행렬의 차수와 동일하다

In [74]:
f = np.array([[1,1,1],[3,2,3,], [4,3,2]])

In [75]:
f

array([[1, 1, 1],
       [3, 2, 3],
       [4, 3, 2]])

In [76]:
np.linalg.det(f)

2.0

In [77]:
np.linalg.matrix_rank(f)

3

## 역행렬 구하기

In [78]:
np.linalg.inv(f)

array([[-2.5,  0.5,  0.5],
       [ 3. , -1. , -0. ],
       [ 0.5,  0.5, -0.5]])

In [79]:
I = f @ np.linalg.inv(f)

In [80]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 행렬의 LU 분해

In [81]:
from scipy import linalg as sp

In [82]:
P, L, U = sp.lu(f)

In [83]:
P

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [84]:
L

array([[ 1.  ,  0.  ,  0.  ],
       [ 0.75,  1.  ,  0.  ],
       [ 0.25, -1.  ,  1.  ]])

In [85]:
U

array([[ 4.  ,  3.  ,  2.  ],
       [ 0.  , -0.25,  1.5 ],
       [ 0.  ,  0.  ,  2.  ]])

In [86]:
np.allclose(P@(L@U), f)

True

## 행렬의 고유값 분해

In [87]:
eigval, eigvec = np.linalg.eig(f)

In [88]:
eigval

array([ 6.31662479, -0.31662479, -1.        ])

In [89]:
eigvec

array([[ 2.56980354e-01,  5.83468866e-01,  2.51287175e-17],
       [ 6.65572661e-01, -8.11007064e-01, -7.07106781e-01],
       [ 7.00695462e-01,  4.27974902e-02,  7.07106781e-01]])

###  값을 검증하기

In [90]:
ie = np.eye(3)

In [91]:
lam = eigval * ie

In [92]:
lam

array([[ 6.31662479, -0.        , -0.        ],
       [ 0.        , -0.31662479, -0.        ],
       [ 0.        , -0.        , -1.        ]])

In [93]:
f

array([[1, 1, 1],
       [3, 2, 3],
       [4, 3, 2]])

In [94]:
eigvec @ lam @ np.linalg.inv(eigvec)

array([[1., 1., 1.],
       [3., 2., 3.],
       [4., 3., 2.]])